//*****************************************************************************
//   This partial class file has been autogenerated by an Objectivity tool.   
//   It provides all of the persistence support for the application class.    
//
//   Do not modify this file directly; instead, change persistence     
//   characteristics by opening and editing the *.pdd file   
//   using the Persistence Designer. 
//*****************************************************************************

namespace CarDesign.Model
{
  using System;
  using Objectivity.Db;
  using Objectivity.Db.Internal;
  using Objectivity.Db.Collections.Specialized;
  public partial class Wheel : ReferenceableObject
  {
    static Wheel() {}

    private static readonly SchemaClass _schemaClass = new SchemaClass("CarDesign.Model.Wheel", 1000003, 1001);

    #region Fields
    private static readonly SchemaAttribute _idField = new SchemaAttribute(_schemaClass, 2, "Id", AttributeKinds.UInt32);
    private static readonly SchemaAttribute _tirePressureField = new SchemaAttribute(_schemaClass, 3, "TirePressure", AttributeKinds.Float64);
    private static readonly SchemaAttribute _locationField = new SchemaAttribute(_schemaClass, 4, "Location", AttributeKinds.UInt32);
    private static readonly SchemaAttribute _rotorField = new SchemaAttribute(_schemaClass, 5, "Rotor", AttributeKinds.Reference, 1000000);
    private static readonly SchemaAttribute _statorField = new SchemaAttribute(_schemaClass, 6, "Stator", AttributeKinds.Reference, 1000001);
    #endregion Fields

    #region Constructors

    protected Wheel(ObjectId id) : base(id) {}
    protected Wheel(PlacementConditions placementConditions, SchemaClass sc) : base(placementConditions, sc)
    {
    }


    #endregion Constructors

    #region Helpers

    new public static Wheel CreateProxyForId(ObjectId id)
    {
      return new Wheel(id);
    }

    new public static int GetClassTypeNumber()
    {
      return _schemaClass.getShapeNumber();
    }


    public static void TieToFdSchema()
    {
      // Empty on purpose.
      // Via static constructor ensures all static schema fields are initialized.
    }

    #endregion Helpers

    #region Properties
    public uint Id
    {
      get {return GetUInt32Value(_idField);}
      set {SetUInt32Value(_idField, value);}
    }

    public double TirePressure
    {
      get {return GetFloat64Value(_tirePressureField);}
      set {SetFloat64Value(_tirePressureField, value);}
    }

    public uint Location
    {
      get {return GetUInt32Value(_locationField);}
      set {SetUInt32Value(_locationField, value);}
    }

    public Rotor Rotor
    {
      get {return (Rotor) GetObject(_rotorField);}
      set {SetObject(_rotorField, value);}
    }

    public Stator Stator
    {
      get {return (Stator) GetObject(_statorField);}
      set {SetObject(_statorField, value);}
    }

    #endregion Properties
  }
}
